// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/core/v1/da/data_availability_header.proto

package da

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// DataAvailabilityHeader contains the row and column roots of the erasure
// coded version of the data in Block.Data.
// Therefore the original Block.Data is arranged in a
// k × k matrix, which is then "extended" to a
// 2k × 2k matrix applying multiple times Reed-Solomon encoding.
// For details see Section 5.2: https://arxiv.org/abs/1809.09044
// or the Celestia specification:
// https://github.com/celestiaorg/celestia-specs/blob/master/src/specs/data_structures.md#availabledataheader
// Note that currently we list row and column roots in separate fields
// (different from the spec).
type DataAvailabilityHeader struct {
	// RowRoot_j = root((M_{j,1} || M_{j,2} || ... || M_{j,2k} ))
	RowRoots [][]byte `protobuf:"bytes,1,rep,name=row_roots,json=rowRoots,proto3" json:"row_roots,omitempty"` // Deprecated: Do not use.
	// ColumnRoot_j = root((M_{1,j} || M_{2,j} || ... || M_{2k,j} ))
	ColumnRoots [][]byte `protobuf:"bytes,2,rep,name=column_roots,json=columnRoots,proto3" json:"column_roots,omitempty"` // Deprecated: Do not use.
	// piece_commitments contains N*k Kate commitments for each piece of the EDS.
	PieceCommitments [][]byte `protobuf:"bytes,3,rep,name=piece_commitments,json=pieceCommitments,proto3" json:"piece_commitments,omitempty"`
	// column_commitments contains N Kate commitments, one for each combined column.
	ColumnCommitments [][]byte `protobuf:"bytes,4,rep,name=column_commitments,json=columnCommitments,proto3" json:"column_commitments,omitempty"`
	// namespace_index stores end-exclusive ranges for namespaces in the ODS.
	NamespaceIndex []*NamespaceRangeEntry `protobuf:"bytes,5,rep,name=namespace_index,json=namespaceIndex,proto3" json:"namespace_index,omitempty"`
}

func (m *DataAvailabilityHeader) Reset()         { *m = DataAvailabilityHeader{} }
func (m *DataAvailabilityHeader) String() string { return proto.CompactTextString(m) }
func (*DataAvailabilityHeader) ProtoMessage()    {}
func (*DataAvailabilityHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c1f9dadbff5429, []int{0}
}
func (m *DataAvailabilityHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataAvailabilityHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DataAvailabilityHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DataAvailabilityHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataAvailabilityHeader.Merge(m, src)
}
func (m *DataAvailabilityHeader) XXX_Size() int {
	return m.Size()
}
func (m *DataAvailabilityHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_DataAvailabilityHeader.DiscardUnknown(m)
}

var xxx_messageInfo_DataAvailabilityHeader proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *DataAvailabilityHeader) GetRowRoots() [][]byte {
	if m != nil {
		return m.RowRoots
	}
	return nil
}

// Deprecated: Do not use.
func (m *DataAvailabilityHeader) GetColumnRoots() [][]byte {
	if m != nil {
		return m.ColumnRoots
	}
	return nil
}

func (m *DataAvailabilityHeader) GetPieceCommitments() [][]byte {
	if m != nil {
		return m.PieceCommitments
	}
	return nil
}

func (m *DataAvailabilityHeader) GetColumnCommitments() [][]byte {
	if m != nil {
		return m.ColumnCommitments
	}
	return nil
}

func (m *DataAvailabilityHeader) GetNamespaceIndex() []*NamespaceRangeEntry {
	if m != nil {
		return m.NamespaceIndex
	}
	return nil
}

// NamespaceRangeEntry maps one namespace id to its [start, end) share range.
type NamespaceRangeEntry struct {
	NamespaceId []byte `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Start       uint32 `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End         uint32 `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (m *NamespaceRangeEntry) Reset()         { *m = NamespaceRangeEntry{} }
func (m *NamespaceRangeEntry) String() string { return proto.CompactTextString(m) }
func (*NamespaceRangeEntry) ProtoMessage()    {}
func (*NamespaceRangeEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4c1f9dadbff5429, []int{1}
}
func (m *NamespaceRangeEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NamespaceRangeEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NamespaceRangeEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NamespaceRangeEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceRangeEntry.Merge(m, src)
}
func (m *NamespaceRangeEntry) XXX_Size() int {
	return m.Size()
}
func (m *NamespaceRangeEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceRangeEntry.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceRangeEntry proto.InternalMessageInfo

func (m *NamespaceRangeEntry) GetNamespaceId() []byte {
	if m != nil {
		return m.NamespaceId
	}
	return nil
}

func (m *NamespaceRangeEntry) GetStart() uint32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *NamespaceRangeEntry) GetEnd() uint32 {
	if m != nil {
		return m.End
	}
	return 0
}

func init() {
	proto.RegisterType((*DataAvailabilityHeader)(nil), "celestia.core.v1.da.DataAvailabilityHeader")
	proto.RegisterType((*NamespaceRangeEntry)(nil), "celestia.core.v1.da.NamespaceRangeEntry")
}

func init() {
	proto.RegisterFile("celestia/core/v1/da/data_availability_header.proto", fileDescriptor_e4c1f9dadbff5429)
}

var fileDescriptor_e4c1f9dadbff5429 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x4b, 0xfb, 0x30,
	0x18, 0xc7, 0x97, 0xf6, 0xb7, 0x1f, 0x9a, 0x55, 0xdd, 0x32, 0x91, 0x9e, 0x6a, 0x1d, 0x08, 0x05,
	0x59, 0xcb, 0xe6, 0xd9, 0x83, 0x53, 0x41, 0x2f, 0x82, 0xbd, 0x08, 0x5e, 0xea, 0xb3, 0x26, 0x6c,
	0x81, 0xb6, 0x29, 0x69, 0xb6, 0xb9, 0x57, 0xa1, 0x2f, 0xcb, 0xe3, 0x8e, 0x1e, 0x65, 0x7b, 0x23,
	0xd2, 0x76, 0x7f, 0x7a, 0xd8, 0xed, 0xc9, 0xf7, 0xf9, 0x7c, 0x9e, 0x24, 0x24, 0xb8, 0x1f, 0xb2,
	0x88, 0x65, 0x8a, 0x83, 0x17, 0x0a, 0xc9, 0xbc, 0x69, 0xcf, 0xa3, 0xe0, 0x51, 0x50, 0x10, 0xc0,
	0x14, 0x78, 0x04, 0x43, 0x1e, 0x71, 0x35, 0x0f, 0xc6, 0x0c, 0x28, 0x93, 0x6e, 0x2a, 0x85, 0x12,
	0xa4, 0xbd, 0x71, 0xdc, 0xdc, 0x71, 0xa7, 0x3d, 0x97, 0x42, 0xe7, 0x53, 0xc3, 0x67, 0xf7, 0xa0,
	0xe0, 0xb6, 0xa2, 0x3d, 0x16, 0x16, 0x39, 0xc7, 0x87, 0x52, 0xcc, 0x02, 0x29, 0x84, 0xca, 0x4c,
	0x64, 0xeb, 0x8e, 0x31, 0xd0, 0x4c, 0xe4, 0x1f, 0x48, 0x31, 0xf3, 0xf3, 0x8c, 0x5c, 0x62, 0x23,
	0x14, 0xd1, 0x24, 0x4e, 0xd6, 0x8c, 0xb6, 0x65, 0x1a, 0x65, 0x5e, 0x62, 0x57, 0xb8, 0x95, 0x72,
	0x16, 0xb2, 0x20, 0x14, 0x71, 0xcc, 0x55, 0xcc, 0x12, 0x95, 0x99, 0x7a, 0xce, 0xfa, 0xcd, 0xa2,
	0x71, 0xb7, 0xcb, 0x49, 0x17, 0x93, 0xf5, 0xcc, 0x2a, 0xfd, 0xaf, 0xa0, 0x5b, 0x65, 0xa7, 0x8a,
	0xbf, 0xe0, 0x93, 0x04, 0x62, 0x96, 0xa5, 0x10, 0xb2, 0x80, 0x27, 0x94, 0x7d, 0x98, 0x75, 0x5b,
	0x77, 0x1a, 0x7d, 0xc7, 0xdd, 0x73, 0x5b, 0xf7, 0x79, 0xc3, 0xfa, 0x90, 0x8c, 0xd8, 0x43, 0xa2,
	0xe4, 0xdc, 0x3f, 0xde, 0x0e, 0x78, 0xca, 0xfd, 0xce, 0x3b, 0x6e, 0xef, 0xc1, 0xc8, 0x05, 0x36,
	0x2a, 0x3b, 0x51, 0x13, 0xd9, 0xc8, 0x31, 0xfc, 0xc6, 0x4e, 0xa6, 0xe4, 0x14, 0xd7, 0x33, 0x05,
	0x52, 0x99, 0x9a, 0x8d, 0x9c, 0x23, 0xbf, 0x5c, 0x90, 0x26, 0xd6, 0x59, 0x42, 0x4d, 0xbd, 0xc8,
	0xf2, 0x72, 0xf0, 0xfa, 0xbd, 0xb4, 0xd0, 0x62, 0x69, 0xa1, 0xdf, 0xa5, 0x85, 0xbe, 0x56, 0x56,
	0x6d, 0xb1, 0xb2, 0x6a, 0x3f, 0x2b, 0xab, 0xf6, 0x76, 0x33, 0xe2, 0x6a, 0x3c, 0x19, 0xba, 0xa1,
	0x88, 0xbd, 0xcd, 0xf9, 0x85, 0x1c, 0x6d, 0xeb, 0x2e, 0xa4, 0xa9, 0x57, 0xbc, 0xa6, 0xb7, 0xe7,
	0x03, 0x0c, 0xff, 0x17, 0xad, 0xeb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0x99, 0x6e, 0xa4,
	0x1e, 0x02, 0x00, 0x00,
}

func (m *DataAvailabilityHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataAvailabilityHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DataAvailabilityHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NamespaceIndex) > 0 {
		for iNdEx := len(m.NamespaceIndex) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NamespaceIndex[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintDataAvailabilityHeader(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.ColumnCommitments) > 0 {
		for iNdEx := len(m.ColumnCommitments) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ColumnCommitments[iNdEx])
			copy(dAtA[i:], m.ColumnCommitments[iNdEx])
			i = encodeVarintDataAvailabilityHeader(dAtA, i, uint64(len(m.ColumnCommitments[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.PieceCommitments) > 0 {
		for iNdEx := len(m.PieceCommitments) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PieceCommitments[iNdEx])
			copy(dAtA[i:], m.PieceCommitments[iNdEx])
			i = encodeVarintDataAvailabilityHeader(dAtA, i, uint64(len(m.PieceCommitments[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ColumnRoots) > 0 {
		for iNdEx := len(m.ColumnRoots) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ColumnRoots[iNdEx])
			copy(dAtA[i:], m.ColumnRoots[iNdEx])
			i = encodeVarintDataAvailabilityHeader(dAtA, i, uint64(len(m.ColumnRoots[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.RowRoots) > 0 {
		for iNdEx := len(m.RowRoots) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RowRoots[iNdEx])
			copy(dAtA[i:], m.RowRoots[iNdEx])
			i = encodeVarintDataAvailabilityHeader(dAtA, i, uint64(len(m.RowRoots[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *NamespaceRangeEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NamespaceRangeEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NamespaceRangeEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.End != 0 {
		i = encodeVarintDataAvailabilityHeader(dAtA, i, uint64(m.End))
		i--
		dAtA[i] = 0x18
	}
	if m.Start != 0 {
		i = encodeVarintDataAvailabilityHeader(dAtA, i, uint64(m.Start))
		i--
		dAtA[i] = 0x10
	}
	if len(m.NamespaceId) > 0 {
		i -= len(m.NamespaceId)
		copy(dAtA[i:], m.NamespaceId)
		i = encodeVarintDataAvailabilityHeader(dAtA, i, uint64(len(m.NamespaceId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDataAvailabilityHeader(dAtA []byte, offset int, v uint64) int {
	offset -= sovDataAvailabilityHeader(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *DataAvailabilityHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RowRoots) > 0 {
		for _, b := range m.RowRoots {
			l = len(b)
			n += 1 + l + sovDataAvailabilityHeader(uint64(l))
		}
	}
	if len(m.ColumnRoots) > 0 {
		for _, b := range m.ColumnRoots {
			l = len(b)
			n += 1 + l + sovDataAvailabilityHeader(uint64(l))
		}
	}
	if len(m.PieceCommitments) > 0 {
		for _, b := range m.PieceCommitments {
			l = len(b)
			n += 1 + l + sovDataAvailabilityHeader(uint64(l))
		}
	}
	if len(m.ColumnCommitments) > 0 {
		for _, b := range m.ColumnCommitments {
			l = len(b)
			n += 1 + l + sovDataAvailabilityHeader(uint64(l))
		}
	}
	if len(m.NamespaceIndex) > 0 {
		for _, e := range m.NamespaceIndex {
			l = e.Size()
			n += 1 + l + sovDataAvailabilityHeader(uint64(l))
		}
	}
	return n
}

func (m *NamespaceRangeEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NamespaceId)
	if l > 0 {
		n += 1 + l + sovDataAvailabilityHeader(uint64(l))
	}
	if m.Start != 0 {
		n += 1 + sovDataAvailabilityHeader(uint64(m.Start))
	}
	if m.End != 0 {
		n += 1 + sovDataAvailabilityHeader(uint64(m.End))
	}
	return n
}

func sovDataAvailabilityHeader(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDataAvailabilityHeader(x uint64) (n int) {
	return sovDataAvailabilityHeader(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DataAvailabilityHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDataAvailabilityHeader
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataAvailabilityHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataAvailabilityHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowRoots", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDataAvailabilityHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RowRoots = append(m.RowRoots, make([]byte, postIndex-iNdEx))
			copy(m.RowRoots[len(m.RowRoots)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ColumnRoots", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDataAvailabilityHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ColumnRoots = append(m.ColumnRoots, make([]byte, postIndex-iNdEx))
			copy(m.ColumnRoots[len(m.ColumnRoots)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PieceCommitments", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDataAvailabilityHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PieceCommitments = append(m.PieceCommitments, make([]byte, postIndex-iNdEx))
			copy(m.PieceCommitments[len(m.PieceCommitments)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ColumnCommitments", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDataAvailabilityHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ColumnCommitments = append(m.ColumnCommitments, make([]byte, postIndex-iNdEx))
			copy(m.ColumnCommitments[len(m.ColumnCommitments)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NamespaceIndex", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDataAvailabilityHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NamespaceIndex = append(m.NamespaceIndex, &NamespaceRangeEntry{})
			if err := m.NamespaceIndex[len(m.NamespaceIndex)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipDataAvailabilityHeader(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NamespaceRangeEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDataAvailabilityHeader
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NamespaceRangeEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NamespaceRangeEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NamespaceId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDataAvailabilityHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NamespaceId = append(m.NamespaceId[:0], dAtA[iNdEx:postIndex]...)
			if m.NamespaceId == nil {
				m.NamespaceId = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			m.Start = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDataAvailabilityHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Start |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field End", wireType)
			}
			m.End = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDataAvailabilityHeader
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.End |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDataAvailabilityHeader(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDataAvailabilityHeader
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDataAvailabilityHeader(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDataAvailabilityHeader
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDataAvailabilityHeader
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDataAvailabilityHeader
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDataAvailabilityHeader
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDataAvailabilityHeader
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDataAvailabilityHeader
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDataAvailabilityHeader        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDataAvailabilityHeader          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDataAvailabilityHeader = fmt.Errorf("proto: unexpected end of group")
)
