// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: celestia/core/v1/proof/proof.proto

package proof

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ShareProof is a KZG polynomial commitment proof that a set of shares exist
// in specific columns of the data square and a commitment proof that those
// column commitments belong to the data root.
type ShareProof struct {
	// data contains the raw shares being proven (original data square shares)
	Data [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	// share_proofs contains KZG multi-proofs, one for each affected column
	// Each proof verifies that the shares in that column satisfy the polynomial
	// commitment via KZG pairing verification
	ShareProofs []*KZGMultiProof `protobuf:"bytes,2,rep,name=share_proofs,json=shareProofs,proto3" json:"share_proofs,omitempty"`
	// namespace_id is the namespace identifier for these shares
	NamespaceId []byte `protobuf:"bytes,3,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	// commitment_proof proves that the column commitments belong to the data root
	CommitmentProof *CommitmentProof `protobuf:"bytes,4,opt,name=commitment_proof,json=commitmentProof,proto3" json:"commitment_proof,omitempty"`
	// namespace_version is the version of the namespace
	NamespaceVersion uint32 `protobuf:"varint,5,opt,name=namespace_version,json=namespaceVersion,proto3" json:"namespace_version,omitempty"`
}

func (m *ShareProof) Reset()         { *m = ShareProof{} }
func (m *ShareProof) String() string { return proto.CompactTextString(m) }
func (*ShareProof) ProtoMessage()    {}
func (*ShareProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53d87d8fb5ec353, []int{0}
}
func (m *ShareProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ShareProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ShareProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ShareProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShareProof.Merge(m, src)
}
func (m *ShareProof) XXX_Size() int {
	return m.Size()
}
func (m *ShareProof) XXX_DiscardUnknown() {
	xxx_messageInfo_ShareProof.DiscardUnknown(m)
}

var xxx_messageInfo_ShareProof proto.InternalMessageInfo

func (m *ShareProof) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ShareProof) GetShareProofs() []*KZGMultiProof {
	if m != nil {
		return m.ShareProofs
	}
	return nil
}

func (m *ShareProof) GetNamespaceId() []byte {
	if m != nil {
		return m.NamespaceId
	}
	return nil
}

func (m *ShareProof) GetCommitmentProof() *CommitmentProof {
	if m != nil {
		return m.CommitmentProof
	}
	return nil
}

func (m *ShareProof) GetNamespaceVersion() uint32 {
	if m != nil {
		return m.NamespaceVersion
	}
	return 0
}

// KZGMultiProof is a KZG proof for a range of shares in a column
// It proves that specific shares belong to the polynomial represented by
// a column commitment via the KZG polynomial commitment scheme
type KZGMultiProof struct {
	// proof is the commitments to the quotient polynomial Q(x) as a single G1 point
	// Serialized in compressed form (48 bytes for BN254)
	Proof []byte `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *KZGMultiProof) Reset()         { *m = KZGMultiProof{} }
func (m *KZGMultiProof) String() string { return proto.CompactTextString(m) }
func (*KZGMultiProof) ProtoMessage()    {}
func (*KZGMultiProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53d87d8fb5ec353, []int{1}
}
func (m *KZGMultiProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KZGMultiProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KZGMultiProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KZGMultiProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KZGMultiProof.Merge(m, src)
}
func (m *KZGMultiProof) XXX_Size() int {
	return m.Size()
}
func (m *KZGMultiProof) XXX_DiscardUnknown() {
	xxx_messageInfo_KZGMultiProof.DiscardUnknown(m)
}

var xxx_messageInfo_KZGMultiProof proto.InternalMessageInfo

func (m *KZGMultiProof) GetProof() []byte {
	if m != nil {
		return m.Proof
	}
	return nil
}

// CommitmentProof proves that column commitments belong to the data root
// This replaces the old RowProof's role in proving row/column inclusion to the root
type CommitmentProof struct {
	// column_proofs contains KZG proofs for each column commitment inclusion
	// These prove that each column commitment satisfies a polynomial relationship
	// with the data root commitment
	ColumnProofs []*KZGMultiProof `protobuf:"bytes,1,rep,name=column_proofs,json=columnProofs,proto3" json:"column_proofs,omitempty"`
	// column_indices contains the indices of columns being proven
	// Used to identify which columns are included in this proof
	ColumnIndices []uint32 `protobuf:"varint,2,rep,packed,name=column_indices,json=columnIndices,proto3" json:"column_indices,omitempty"`
	// root_commitment is the data root as a point commitment (optional, for verification)
	RootCommitment []byte `protobuf:"bytes,3,opt,name=root_commitment,json=rootCommitment,proto3" json:"root_commitment,omitempty"`
}

func (m *CommitmentProof) Reset()         { *m = CommitmentProof{} }
func (m *CommitmentProof) String() string { return proto.CompactTextString(m) }
func (*CommitmentProof) ProtoMessage()    {}
func (*CommitmentProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_e53d87d8fb5ec353, []int{2}
}
func (m *CommitmentProof) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CommitmentProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CommitmentProof.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CommitmentProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitmentProof.Merge(m, src)
}
func (m *CommitmentProof) XXX_Size() int {
	return m.Size()
}
func (m *CommitmentProof) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitmentProof.DiscardUnknown(m)
}

var xxx_messageInfo_CommitmentProof proto.InternalMessageInfo

func (m *CommitmentProof) GetColumnProofs() []*KZGMultiProof {
	if m != nil {
		return m.ColumnProofs
	}
	return nil
}

func (m *CommitmentProof) GetColumnIndices() []uint32 {
	if m != nil {
		return m.ColumnIndices
	}
	return nil
}

func (m *CommitmentProof) GetRootCommitment() []byte {
	if m != nil {
		return m.RootCommitment
	}
	return nil
}

func init() {
	proto.RegisterType((*ShareProof)(nil), "celestia.core.v1.proof.ShareProof")
	proto.RegisterType((*KZGMultiProof)(nil), "celestia.core.v1.proof.KZGMultiProof")
	proto.RegisterType((*CommitmentProof)(nil), "celestia.core.v1.proof.CommitmentProof")
}

func init() {
	proto.RegisterFile("celestia/core/v1/proof/proof.proto", fileDescriptor_e53d87d8fb5ec353)
}

var fileDescriptor_e53d87d8fb5ec353 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x6a, 0xe3, 0x30,
	0x18, 0x8c, 0xf2, 0xb3, 0x87, 0xcf, 0x76, 0x92, 0x15, 0xcb, 0xe2, 0x93, 0xf1, 0x1a, 0x42, 0x0c,
	0x4b, 0x6c, 0x92, 0xbe, 0x41, 0x7b, 0x48, 0xd3, 0x52, 0x28, 0x2e, 0xf4, 0x90, 0x4b, 0x70, 0x64,
	0x35, 0x11, 0x8d, 0x2d, 0x63, 0x29, 0x79, 0x8c, 0xd2, 0x17, 0xe9, 0x7b, 0xf4, 0x98, 0x63, 0x8f,
	0x25, 0x79, 0x91, 0x62, 0xcb, 0x71, 0x48, 0x69, 0x0f, 0xbd, 0x08, 0x69, 0x34, 0x9a, 0x19, 0x0d,
	0x1f, 0x38, 0x84, 0xae, 0xa8, 0x90, 0x2c, 0xf4, 0x09, 0xcf, 0xa8, 0xbf, 0x19, 0xfa, 0x69, 0xc6,
	0xf9, 0x83, 0x5a, 0xbd, 0x34, 0xe3, 0x92, 0xe3, 0xbf, 0x07, 0x8e, 0x97, 0x73, 0xbc, 0xcd, 0xd0,
	0x2b, 0x6e, 0x9d, 0xa7, 0x3a, 0xc0, 0xdd, 0x32, 0xcc, 0xe8, 0x6d, 0x7e, 0xc4, 0x18, 0x9a, 0x51,
	0x28, 0x43, 0x13, 0xd9, 0x0d, 0x57, 0x0f, 0x8a, 0x3d, 0xbe, 0x04, 0x5d, 0xe4, 0x8c, 0x59, 0xf1,
	0x42, 0x98, 0x75, 0xbb, 0xe1, 0x6a, 0xa3, 0x9e, 0xf7, 0xb5, 0xa2, 0x77, 0x3d, 0x1d, 0xdf, 0xac,
	0x57, 0x92, 0x15, 0x82, 0x81, 0x26, 0x2a, 0x71, 0x81, 0xff, 0x81, 0x9e, 0x84, 0x31, 0x15, 0x69,
	0x48, 0xe8, 0x8c, 0x45, 0x66, 0xc3, 0x46, 0xae, 0x1e, 0x68, 0x15, 0x36, 0x89, 0x70, 0x00, 0x5d,
	0xc2, 0xe3, 0x98, 0xc9, 0x98, 0x26, 0x52, 0x39, 0x9a, 0x4d, 0x1b, 0xb9, 0xda, 0xa8, 0xff, 0x9d,
	0xe1, 0x45, 0xc5, 0x57, 0x96, 0x1d, 0x72, 0x0a, 0xe0, 0xff, 0xf0, 0xfb, 0x68, 0xbb, 0xa1, 0x99,
	0x60, 0x3c, 0x31, 0x5b, 0x36, 0x72, 0x8d, 0xa0, 0x5b, 0x5d, 0xdc, 0x2b, 0xdc, 0xe9, 0x81, 0x71,
	0xf2, 0x03, 0xfc, 0x07, 0x5a, 0x2a, 0x06, 0x2a, 0xd2, 0xaa, 0x83, 0xf3, 0x82, 0xa0, 0xf3, 0xc9,
	0x18, 0x5f, 0x81, 0x41, 0xf8, 0x6a, 0x1d, 0x27, 0x87, 0xa6, 0xd0, 0x4f, 0x9a, 0xd2, 0xd5, 0xdb,
	0xb2, 0xaa, 0x1e, 0xb4, 0x4b, 0x2d, 0x96, 0x44, 0x8c, 0x50, 0x55, 0xbb, 0x11, 0x94, 0x0e, 0x13,
	0x05, 0xe2, 0x3e, 0x74, 0x32, 0xce, 0xe5, 0xec, 0xf8, 0xe5, 0xb2, 0xd4, 0x76, 0x0e, 0x1f, 0x03,
	0x9e, 0x8f, 0x5f, 0x77, 0x16, 0xda, 0xee, 0x2c, 0xf4, 0xbe, 0xb3, 0xd0, 0xf3, 0xde, 0xaa, 0x6d,
	0xf7, 0x56, 0xed, 0x6d, 0x6f, 0xd5, 0xa6, 0x83, 0x05, 0x93, 0xcb, 0xf5, 0xdc, 0x23, 0x3c, 0xf6,
	0x0f, 0x41, 0x79, 0xb6, 0xa8, 0xf6, 0x83, 0x30, 0x4d, 0xfd, 0xf4, 0x71, 0xa1, 0xc6, 0x69, 0xfe,
	0xab, 0x98, 0xa7, 0xb3, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x47, 0x94, 0x0b, 0x75, 0x02,
	0x00, 0x00,
}

func (m *ShareProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ShareProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ShareProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NamespaceVersion != 0 {
		i = encodeVarintProof(dAtA, i, uint64(m.NamespaceVersion))
		i--
		dAtA[i] = 0x28
	}
	if m.CommitmentProof != nil {
		{
			size, err := m.CommitmentProof.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintProof(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.NamespaceId) > 0 {
		i -= len(m.NamespaceId)
		copy(dAtA[i:], m.NamespaceId)
		i = encodeVarintProof(dAtA, i, uint64(len(m.NamespaceId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ShareProofs) > 0 {
		for iNdEx := len(m.ShareProofs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ShareProofs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProof(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Data) > 0 {
		for iNdEx := len(m.Data) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Data[iNdEx])
			copy(dAtA[i:], m.Data[iNdEx])
			i = encodeVarintProof(dAtA, i, uint64(len(m.Data[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *KZGMultiProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KZGMultiProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KZGMultiProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintProof(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CommitmentProof) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CommitmentProof) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CommitmentProof) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RootCommitment) > 0 {
		i -= len(m.RootCommitment)
		copy(dAtA[i:], m.RootCommitment)
		i = encodeVarintProof(dAtA, i, uint64(len(m.RootCommitment)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ColumnIndices) > 0 {
		dAtA3 := make([]byte, len(m.ColumnIndices)*10)
		var j2 int
		for _, num := range m.ColumnIndices {
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		i -= j2
		copy(dAtA[i:], dAtA3[:j2])
		i = encodeVarintProof(dAtA, i, uint64(j2))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ColumnProofs) > 0 {
		for iNdEx := len(m.ColumnProofs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ColumnProofs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintProof(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintProof(dAtA []byte, offset int, v uint64) int {
	offset -= sovProof(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ShareProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Data) > 0 {
		for _, b := range m.Data {
			l = len(b)
			n += 1 + l + sovProof(uint64(l))
		}
	}
	if len(m.ShareProofs) > 0 {
		for _, e := range m.ShareProofs {
			l = e.Size()
			n += 1 + l + sovProof(uint64(l))
		}
	}
	l = len(m.NamespaceId)
	if l > 0 {
		n += 1 + l + sovProof(uint64(l))
	}
	if m.CommitmentProof != nil {
		l = m.CommitmentProof.Size()
		n += 1 + l + sovProof(uint64(l))
	}
	if m.NamespaceVersion != 0 {
		n += 1 + sovProof(uint64(m.NamespaceVersion))
	}
	return n
}

func (m *KZGMultiProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovProof(uint64(l))
	}
	return n
}

func (m *CommitmentProof) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ColumnProofs) > 0 {
		for _, e := range m.ColumnProofs {
			l = e.Size()
			n += 1 + l + sovProof(uint64(l))
		}
	}
	if len(m.ColumnIndices) > 0 {
		l = 0
		for _, e := range m.ColumnIndices {
			l += sovProof(uint64(e))
		}
		n += 1 + sovProof(uint64(l)) + l
	}
	l = len(m.RootCommitment)
	if l > 0 {
		n += 1 + l + sovProof(uint64(l))
	}
	return n
}

func sovProof(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProof(x uint64) (n int) {
	return sovProof(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ShareProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProof
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ShareProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ShareProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data, make([]byte, postIndex-iNdEx))
			copy(m.Data[len(m.Data)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareProofs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShareProofs = append(m.ShareProofs, &KZGMultiProof{})
			if err := m.ShareProofs[len(m.ShareProofs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NamespaceId", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NamespaceId = append(m.NamespaceId[:0], dAtA[iNdEx:postIndex]...)
			if m.NamespaceId == nil {
				m.NamespaceId = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentProof", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CommitmentProof == nil {
				m.CommitmentProof = &CommitmentProof{}
			}
			if err := m.CommitmentProof.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NamespaceVersion", wireType)
			}
			m.NamespaceVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NamespaceVersion |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipProof(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProof
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KZGMultiProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProof
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KZGMultiProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KZGMultiProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof[:0], dAtA[iNdEx:postIndex]...)
			if m.Proof == nil {
				m.Proof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProof(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProof
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CommitmentProof) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProof
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CommitmentProof: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CommitmentProof: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ColumnProofs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ColumnProofs = append(m.ColumnProofs, &KZGMultiProof{})
			if err := m.ColumnProofs[len(m.ColumnProofs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v uint32
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowProof
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ColumnIndices = append(m.ColumnIndices, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowProof
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthProof
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthProof
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ColumnIndices) == 0 {
					m.ColumnIndices = make([]uint32, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint32
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowProof
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint32(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ColumnIndices = append(m.ColumnIndices, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ColumnIndices", wireType)
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RootCommitment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProof
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthProof
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthProof
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RootCommitment = append(m.RootCommitment[:0], dAtA[iNdEx:postIndex]...)
			if m.RootCommitment == nil {
				m.RootCommitment = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProof(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProof
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProof(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProof
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProof
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProof
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProof
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProof
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProof
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProof        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProof          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProof = fmt.Errorf("proto: unexpected end of group")
)
